puts "The Students of my cohort at Makers Academy"
puts "---------------"
puts "Bumblebee Man"
puts "Disco Stu"
puts "Dr. Nick Riveria"
puts "Edna Krabappel"
puts "Lionel Hutz"
puts "Patty Bouvier"
puts "Eleanor Abernathy"
print "Overall, we have "
print 6
puts " outstanding students"